### ISSUE TITLE
problem on installation

### ISSUE THREAD

**Issue by loran750** [Matthuffy/henfire#1]
hello

on step 3 of install.php i get this error :

` Connecting to database..
Connection [ok]
 Saving information ... Inserting user ...
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx_henfire.mh_settings' doesn't exist in /home/xxx/henfire/install/Db.php:143 Stack trace: #0 /home/xxx/henfire/install/Db.php(143): PDO->query('TRUNCATE TABLE ...') #1 /home/xxx/henfire/install.php(397): Db->raw('TRUNCATE TABLE ...') #2 {main} thrown in /home/xxx/henfire/install/Db.php on line 143`

**Comment by Matthuffy** [comment]
really sorry. i must have uploaded the wrong one. I was certain it was the correct version but was in a rush traveling and had promised a few people I would get it up before I left. i will be back tomorrow and will get it installed and tested to be sure I upload the correct one.

**Comment by Matthuffy** [comment]
Updated and tested the upload this time.
