### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by KwabenaOduro** [Matthuffy/henfire#2]
had this error whiles running on xampp server 

Warning: require(/Applications/XAMPP/xamppfiles/htdocs/henfire-master/protected/common/config/main.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/henfire-master/index.php on line 11

Fatal error: require(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/henfire-master/protected/common/config/main.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/henfire-master/index.php on line 11

**Comment by Matthuffy** [comment]
Main.php was not created on install. have you used the latest commit? also which php version are you using on xampp?

**Comment by KwabenaOduro** [comment]
Thanks Matthuffy.Currently using php7 on xampp

**Comment by Matthuffy** [comment]
To be blunt, really hard to assist you on a localhost setup on your mac as no idea how you have it setup. i am using ampps and testing on that is all fine. however, I have no idea how you have set it up for your test environment.

your issue though is that main.php is not being created in the install process so could be a permission error that your apache does not have write access on your machine in xampp.

Yes you should be using php 7+ will work with lower but not recommended at all to bother with lower than 7.

**Comment by Matthuffy** [comment]
I just realized. You did not install it have you? you have uploaded and then gone to index.php. You must install it. please read the readme on first page.

**Comment by KwabenaOduro** [comment]
Thanks for the correction will do exactly that.Rally appreciate the help
